name: movies
description: "A new Flutter project that provides users with the latest films"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_toggle_switch: ^0.8.5
  flutter_svg: ^2.2.1
  easy_localization: ^3.0.8

  # Firebase Dependencies (latest stable)
  firebase_auth: ^5.0.1
  google_sign_in: ^6.2.1
  firebase_ui_auth: ^1.3.1 # Optional for ready-made auth UI
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Authentication image/
    - assets/images/avatars/
    - assets/images/language_images/
    - assets/images/