// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDC02B9cx91T-84XuwWwueN2NplZqSjPM',
    appId: '1:158516261779:android:3b0e93d1b2bb1f575bae66',
    messagingSenderId: '158516261779',
    projectId: 'movies-20f8c',
    storageBucket: 'movies-20f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4tG8nUsvb3R4vOXisEoVr11dNG1gstZ0',
    appId: '1:158516261779:ios:8633be276657781f5bae66',
    messagingSenderId: '158516261779',
    projectId: 'movies-20f8c',
    storageBucket: 'movies-20f8c.firebasestorage.app',
    androidClientId: '158516261779-n7m6nvi6aoe43cjjchd936g9l7je8co1.apps.googleusercontent.com',
    iosClientId: '158516261779-6qv2ipb7ur48aoco3j0ntfrq15u2693m.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
